version: 2
updates:
    - package-ecosystem: npm
      versioning-strategy: increase
      directory: /
      schedule:
          interval: weekly
      ignore:
          # Updated with the monthly z2m release
          - dependency-name: zigbee-herdsman-converters
      groups:
          all:
              applies-to: version-updates
              patterns:
                  - '*'
      commit-message:
          prefix: fix(ignore)
