const utils = require('./utils');
/**
 * This script generates the supported devices json.
 */

let devices = [...require('zigbee-herdsman-converters').devices];
const vendors = new Set();

for (const device of devices) {
    if (device.whiteLabel) {
        for (const whiteLabel of device.whiteLabel) {
            const whiteLabelDevice = {
                ...device,
                model: whiteLabel.model,
                vendor: whiteLabel.vendor,
                description: whiteLabel.description,
                whiteLabelOf: device,
            };

            delete whiteLabelDevice.whiteLabel;

            devices.push(whiteLabelDevice);
        }
    }
}

devices = devices.map((d) => {
    const model = d.whiteLabelOf ? d.whiteLabelOf.model : d.model;
    const image = utils.getImage(d, '');
    const description = d.description || d.whiteLabelOf.description;
    const link = `../devices/${ utils.normalizeModel(model) }.html`;
    const exposes = Array.from(new Set(
        d.exposes
            .map((e) => e.name ? e.name : e.type)
            .filter((e) => e !== 'linkquality' && e !== 'effect'),
    ));

    vendors.add(d.vendor);

    return {
        model,
        vendor: d.vendor,
        description,
        image,
        link,
        exposes,
    };
});


// Shuffle - give the visitors some hints for "other" devices ;)
devices.sort(() => Math.random() - 0.5);

const pageTemplate = `---
---
<!---
This file has been generated, do not edit this file manually!
-->
# Supported devices

Currently **${ devices.length }** devices are supported from **${ vendors.size }** different vendors.

In case you own a Zigbee device which is **NOT** listed here, please see
[How to support new devices](../how_tos/how_to_support_new_devices.md).

<div id="supported-devices-app"></div>

<script>
window.ZIGBEE2MQTT_SUPPORTED_DEVICES = ${ JSON.stringify(devices) };
</script>
<script defer="defer" src="../assets/device-overview/js/chunk-vendors.js" type="module"></script>
<script defer="defer" src="../assets/device-overview/js/app.js" type="module"></script>
<link href="../assets/device-overview/css/app.css" rel="stylesheet">
<script defer="defer" src="../assets/device-overview/js/chunk-vendors-legacy.js" nomodule=""></script>
<script defer="defer" src="../assets/device-overview/js/app-legacy.js" nomodule=""></script>
`;

module.exports = pageTemplate;
